### PR TITLE
fix replace-region-or-line can't find region

### PR DESCRIPTION
**Pull request by lyjdwh**

### CODE REVIEW

**Comment by manateelazycat** [comment]
I do not think this is a correct patch, because the current version is already such a deal of.

**Comment by manateelazycat** [comment]
Thanks anyway.

**Comment by lyjdwh** [comment]
But when I use thing-replace-region-or-line to replace a region, I get the message "No region here".

**Comment by manateelazycat** [comment]
> But when I use thing-replace-region-or-line to replace a region, I get the message "No region here".

you can open new issue with details steps

patch is not correct

**Pull request closed without merging**
